# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YjuxogAQJDd8F8ecCtBctUrweN76WSoq
"""

!pip install streamlit transformers torch pillow gtts

# app.py - Storytelling App for kids (3-10 years)
# Uses Hugging Face Transformers for captioning + story generation,
# and gTTS for text-to-speech.

import streamlit as st
from transformers import pipeline
from PIL import Image
from gtts import gTTS
import tempfile
import os

# -------------------------------------------------------------------
# Helper functions (with caching to speed up the app)
# -------------------------------------------------------------------

@st.cache_resource
def load_captioning_model():
    """Load the image captioning model once and cache it."""
    return pipeline("image-to-text", model="Salesforce/blip-image-captioning-base")

@st.cache_resource
def load_story_model():
    """Load the text generation model (distilgpt2 is small and fast)."""
    return pipeline("text-generation", model="distilgpt2")

def img2text(image):
    """
    Convert a PIL image into a caption using BLIP.
    """
    captioner = load_captioning_model()
    # The pipeline expects a list of images or a single image
    result = captioner(image)
    caption = result[0]['generated_text']
    return caption

def text2story(caption):
    """
    Generate a 50-100 word children's story from the caption.
    """
    generator = load_story_model()
    # Craft a prompt suitable for kids
    prompt = f"Once upon a time, {caption}. Write a short children's story (50-100 words):"

    # Generate text
    output = generator(
        prompt,
        max_new_tokens=150,          # enough for ~100 words
        do_sample=True,
        temperature=0.8,
        pad_token_id=50256,          # distilgpt2's eos_token_id
        truncation=True
    )

    full_story = output[0]['generated_text']
    # Remove the prompt from the beginning if necessary
    if full_story.startswith(prompt):
        story = full_story[len(prompt):].strip()
    else:
        story = full_story.strip()

    # If the story is still too short or empty, add a fallback
    if len(story.split()) < 20:
        story = f"{caption} It was a wonderful day full of laughter and fun. Everyone learned something new and lived happily ever after."

    return story

def text2audio(story_text):
    """
    Convert the story text to an MP3 audio file using gTTS.
    Returns the path to a temporary audio file.
    """
    # gTTS supports multiple languages; 'en' is fine for English stories
    tts = gTTS(text=story_text, lang='en', slow=False)

    # Save to a temporary file so Streamlit can play it
    with tempfile.NamedTemporaryFile(delete=False, suffix='.mp3') as tmp_file:
        audio_path = tmp_file.name
        tts.save(audio_path)

    return audio_path

# -------------------------------------------------------------------
# Streamlit User Interface
# -------------------------------------------------------------------

def main():
    st.set_page_config(page_title="Kid's Storyteller", page_icon="📖")
    st.title("✨ Storyteller for Kids ✨")
    st.write("Upload a picture, and I will create a **magical story** for you (50–100 words) and read it aloud!")

    # Image uploader
    uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

    if uploaded_file is not None:
        # Display the image
        image = Image.open(uploaded_file)
        st.image(image, caption="Your picture", use_container_width=True)

        # Button to generate story
        if st.button("Tell me a story!"):
            with st.spinner("Looking at the picture..."):
                caption = img2text(image)
                st.info(f"📷 I see: _{caption}_")

            with st.spinner("Writing a story..."):
                story = text2story(caption)
                # Ensure story length (rough check)
                word_count = len(story.split())
                if word_count < 50:
                    story += " And they all had a wonderful time. The end."
                elif word_count > 120:
                    story = " ".join(story.split()[:120]) + "... The end."
                st.success("📖 Here is your story:")
                st.write(story)

            with st.spinner("Recording audio..."):
                audio_file = text2audio(story)
                st.audio(audio_file, format='audio/mp3')
                # Clean up temporary file (optional)
                os.unlink(audio_file)

if __name__ == "__main__":
    main()